Took into account review from the assistants
Drone3D-Team/Drone3D pull request #216
Opened 2021-05-06 13:57 UTC by Anghul

2021-05-06 19:50 UTC, jonasblanc requested changes

2021-05-06 20:57 UTC, Anghul commented on app/src/main/java/ch/epfl/sdp/drone3d/ui/drone/DroneConnectActivity.kt
> +        private val pattern: Pattern = Pattern.compile(REGEX)
No, the type Pattern cannot be a const

2021-05-07 06:34 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/ui/drone/DroneConnectActivity.kt
> +        private val pattern: Pattern = Pattern.compile(REGEX)
Ok

2021-05-07 06:34 UTC, jonasblanc approved these changes

2021-05-07 07:39 UTC, Jorque approved these changes
Seems good

2021-05-07 07:41 UTC, merged

2021-05-07 07:43 UTC, loh0um approved these changes