Add an edit button in ItineraryShowActivity
Drone3D-Team/Drone3D pull request #276
Opened 2021-05-14 21:35 UTC by jonasblanc

Add an edit button in ItineraryShowActivity to let the user edit a mapping mission he loaded from browse Itinerary.
When the button is pressed it opens ItineraryCreateActivity with the same area, flightHeight and strategy.

2021-05-16 18:19 UTC, GabrielFleischer requested changes
A simplifucation could be done

2021-05-16 18:19 UTC, GabrielFleischer commented on app/src/main/java/ch/epfl/sdp/drone3d/ui/mission/ItineraryCreateActivity.kt
> +            }
This could be simplified :

```suggestion
            initialArea.forEach { areaBuilder.addVertex(it) }
```

2021-05-16 20:06 UTC, GabrielFleischer approved these changes

2021-05-17 20:17 UTC, loh0um approved these changes
It would be nice to be able to modify the mission that we update instead of creating a new one. Passing the name or an ID from ItineraryShow to ItineraryCreate and then updating the current mission in the database instead of creating a new one from ItinerarySave would be more intuitive. But it can be done in a later PR and it is more a "nice to have" than a "must have" and since we don't have much time left, we probably won't have time to implement it

2021-05-17 20:17 UTC, loh0um commented on app/src/main/res/layout/activity_itinerary_show.xml
> +        android:layout_gravity="bottom|end"
I think that you don't have to use gravity in a constraintlayout if you place your constraints correctly, but it's a detail

2021-05-18 07:46 UTC, merged