Major code review
Drone3D-Team/Drone3D pull request #324
Opened 2021-05-27 20:28 UTC by GabrielFleischer

The PR aims at improving the code style.

Style issues and typos were addressed and a complete reformat was done

2021-05-27 20:59 UTC, jonasblanc requested changes

2021-05-27 20:59 UTC, jonasblanc commented on app/src/androidTest/java/ch/epfl/sdp/drone3d/ui/mission/MissionPicturesActivityTest.kt
> +package ch.epfl.sdp.drone3d.ui.mission
Same remark as the other PR: missing header

2021-05-27 20:59 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/service/api/drone/DroneService.kt
>  interface DroneService {
Interface documentation missing.

2021-05-27 20:59 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/service/impl/drone/DroneServerFactoryImpl.kt
> +class DroneServerFactoryImpl : DroneServerFactory {
A documentation about the implemtation would be appreciated

2021-05-27 20:59 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/service/impl/storage/FirebaseUser.kt
> +class FirebaseUser @Inject constructor(
A documentation about the class would be nice

2021-05-27 20:59 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/ui/weather/WeatherInfoActivity.kt
> +                getString(R.string.info_visibility_km, (visibility / 1000).toString())
Maybe a constant for 1000 would improve the comprehension

2021-05-28 06:35 UTC, jonasblanc approved these changes

2021-05-28 07:27 UTC, Anghul approved these changes
Good job

2021-06-02 14:03 UTC, merged