Add hilt integeration and login/register UI implementation
Drone3D-Team/Drone3D pull request #62
Opened 2021-03-18 15:43 UTC by GabrielFleischer

2021-03-18 18:12 UTC, Jorque requested changes
Typo in file name otherwise seems good.

2021-03-18 18:12 UTC, Jorque commented on app/src/main/java/ch/epfl/sdp/drone3d/auth/AuthetificationModule.kt
> +package ch.epfl.sdp.drone3d.auth
Typo in file name

2021-03-18 19:27 UTC, jonasblanc approved these changes

2021-03-18 22:07 UTC, loh0um approved these changes

2021-03-19 08:29 UTC, Jorque approved these changes

2021-03-19 08:34 UTC, merged