Work anghul drone utils and instance
Drone3D-Team/Drone3D pull request #84
Opened 2021-03-25 15:39 UTC by Anghul

2021-03-25 21:07 UTC, jonasblanc commented
A description would be useful to quickly understand the PR

2021-03-25 21:27 UTC, jonasblanc requested changes
We should probably state which files we took from Fly2Find

2021-03-25 21:27 UTC, jonasblanc commented on app/src/androidTest/java/ch/epfl/sdp/drone3d/drone/DroneInstanceMock.kt
> +    val droneSystem: System = Mockito.mock(System::class.java)
We used the convention to import Mockito.* and not use Mockito. ... in code

2021-03-25 21:27 UTC, jonasblanc commented on app/src/main/java/ch/epfl/sdp/drone3d/MainActivity.kt
> +                text = "See connected drone"
The button text should not be in the code

2021-03-25 21:27 UTC, jonasblanc commented on app/src/main/res/values-round/strings.xml
> +<resources>
Why is this file needed ?

2021-03-25 21:27 UTC, jonasblanc commented on app/src/main/res/values/dimens.xml
> +<?xml version="1.0" encoding="utf-8"?>
Why is this file needed ?

2021-03-25 23:23 UTC, GabrielFleischer requested changes

2021-03-25 23:23 UTC, GabrielFleischer commented on app/build.gradle
> +    compileOnly 'com.google.android.wearable:wearable:2.8.1'
I don't think those libraries are needed

2021-03-25 23:23 UTC, GabrielFleischer commented on app/src/main/res/values/strings.xml
> +    <string name="hello_world">Hello Square World!</string>
This can be removed

2021-03-26 07:21 UTC, Anghul commented on app/src/main/res/values-round/strings.xml
> +<resources>
Nothing, it was created by error

2021-03-26 07:22 UTC, Anghul commented on app/src/main/res/values/dimens.xml
> +<?xml version="1.0" encoding="utf-8"?>
Nothing, it was created by error

2021-03-26 08:12 UTC, GabrielFleischer approved these changes

2021-03-26 08:12 UTC, GabrielFleischer approved these changes

2021-03-26 08:13 UTC, jonasblanc approved these changes

2021-03-26 08:37 UTC, merged